### ISSUE TITLE
なんでこれ出る？ DBに残ったまま？ http://renew.oirase-fm.com/museum/dictionary/lists/detail/?id=1/?id=5&category_name=樹木

### ISSUE THREAD

**Issue by himhong** [mogamin/dictionary#16]

**Comment by himhong** [comment]
http://renew.oirase-fm.com/museum/dictionary/lists/detail/?id=1/?id=5&category_name=樹木

**Comment by mogamin** [comment]
削除フラグが立っているものは取得できないように修正しました。

**Comment by mogamin** [comment]
http://dict.moshouse.com/p/index.php?s=api_get_item&item_id=1/?id=5&callback=itemDetail&callback=itemDetail&_=1552524256503

oirase.moshouse.comはソースコードがアップデートされていないので、上記のURLで叩くと取得できないことがわかる。
