### ISSUE TITLE
item詳細でもカテゴリー名出すか、idからカテゴリー名引っ張るAPIください！

### ISSUE THREAD

**Issue by himhong** [mogamin/dictionary#17]

**Comment by mogamin** [comment]
以下のAPIを追加しました。
https://github.com/mogamin/dictionary/issues/14

**Comment by mogamin** [comment]
http://dict.moshouse.com/p/index.php?s=api_get_item&item_id=23
上記URLで各種マスタ名も取得できるようにした。
